import { Link } from "react-router-dom";
import { useState } from "react";
import { ChevronDown, Heart, Mail, MapPin, Phone, Shield, Target, Users } from "lucide-react";
import Card from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";
import Textarea from "@/components/ui/Textarea";
import { FAQS, PRIVACY_SECTIONS, TERMS_SECTIONS } from "@/constants";
import { useToast } from "@/context/ToastContext";

export function AboutPage() { return <div><PageHero title="About NayePankh Foundation" text="Building a kinder, more equitable future through community-led action." /><section className="py-16"><div className="max-w-5xl mx-auto px-4 grid md:grid-cols-2 gap-8 items-center"><div><p className="text-primary-600 font-semibold text-sm uppercase tracking-wide">Our mission</p><h2 className="mt-2 text-3xl font-bold font-display text-gray-900 dark:text-gray-100">Small actions. Lasting change.</h2><p className="mt-4 text-gray-600 dark:text-gray-400 leading-relaxed">NayePankh Foundation connects generous people with meaningful causes across India. From education and healthcare to emergency relief, we believe communities thrive when everyone has the opportunity to participate in change.</p><p className="mt-4 text-gray-600 dark:text-gray-400 leading-relaxed">Our fundraising portal makes giving transparent and personal. Supporters can raise funds through their own networks, and donors can see the difference their contribution makes.</p></div><Card padding="lg" className="bg-gradient-to-br from-primary-600 to-secondary-600 text-white border-0"><Heart className="w-10 h-10 mb-5" /><h3 className="text-2xl font-bold font-display">Together, we rise.</h3><p className="mt-3 opacity-90">Every donation is a feather in a larger wing — lifting families, children, and communities toward a brighter tomorrow.</p></Card></div></section><section className="py-16 bg-gray-50 dark:bg-gray-950"><div className="max-w-5xl mx-auto px-4 grid sm:grid-cols-3 gap-6">{[{icon: Target, title:"Purpose-led", text:"Every campaign is selected for measurable community impact."},{icon: Shield, title:"Transparent", text:"Clear progress, secure payments, and responsible stewardship."},{icon: Users, title:"Community-powered", text:"Real change grows when people work together."}].map(({icon:Icon,title,text})=><Card key={title} padding="lg" className="text-center"><Icon className="w-9 h-9 text-primary-600 mx-auto mb-4"/><h3 className="font-bold text-gray-900 dark:text-gray-100">{title}</h3><p className="mt-2 text-sm text-gray-500">{text}</p></Card>)}</div></section></div> }

export function FAQPage() { const [open,setOpen]=useState<number|null>(0); return <div><PageHero title="Frequently Asked Questions" text="Everything you need to know about donating and fundraising with us." /><section className="py-14"><div className="max-w-3xl mx-auto px-4 space-y-3">{FAQS.map((faq,i)=><Card key={faq.question} padding="none"><button onClick={()=>setOpen(open===i?null:i)} className="w-full flex items-center justify-between text-left p-5"><span className="font-semibold text-gray-900 dark:text-gray-100">{faq.question}</span><ChevronDown className={`w-5 h-5 text-gray-400 transition-transform ${open===i?'rotate-180':''}`}/></button>{open===i&&<p className="px-5 pb-5 text-sm text-gray-600 dark:text-gray-400 leading-relaxed">{faq.answer}</p>}</Card>)}</div></section></div> }

export function ContactPage() { const {toast}=useToast(); const [sent,setSent]=useState(false); const submit=(e:React.FormEvent)=>{e.preventDefault();setSent(true);toast("Your message has been received. Our team will get back to you soon.");}; return <div><PageHero title="Get in touch" text="Have a question, partnership idea, or want to volunteer? We would love to hear from you." /><section className="py-14"><div className="max-w-5xl mx-auto px-4 grid md:grid-cols-5 gap-8"><div className="md:col-span-2 space-y-4"><ContactItem icon={<Mail/>} title="Email" text="contact@naye-pankh.org"/><ContactItem icon={<Phone/>} title="Phone" text="+91 98765 43210"/><ContactItem icon={<MapPin/>} title="Visit us" text="New Delhi, India"/></div><Card padding="lg" className="md:col-span-3">{sent?<div className="py-12 text-center"><Heart className="w-12 h-12 text-primary-500 mx-auto"/><h2 className="mt-4 text-xl font-bold">Thank you for reaching out</h2><p className="mt-2 text-sm text-gray-500">We will be in touch shortly.</p></div>:<form onSubmit={submit} className="space-y-4"><Input label="Your name" required/><Input label="Email address" type="email" required/><Input label="Subject" required/><Textarea label="Message" rows={5} required/><Button type="submit">Send Message</Button></form>}</Card></div></section></div> }

export function PolicyPage({terms=false}:{terms?:boolean}) { const sections=terms?TERMS_SECTIONS:PRIVACY_SECTIONS; return <div><PageHero title={terms?"Terms & Conditions":"Privacy Policy"} text={terms?"The guidelines that keep our community safe and accountable.":"How we protect and use the information you share with us."}/><section className="py-14"><div className="max-w-3xl mx-auto px-4 space-y-6">{sections.map(section=><div key={section.title}><h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">{section.title}</h2><p className="mt-2 text-sm text-gray-600 dark:text-gray-400 leading-relaxed">{section.content}</p></div>)}</div></section></div> }

function PageHero({title,text}:{title:string;text:string}){return <section className="bg-gradient-to-br from-primary-50 to-white dark:from-gray-950 dark:to-gray-900 py-16"><div className="max-w-7xl mx-auto px-4 text-center"><h1 className="text-4xl font-bold font-display text-gray-900 dark:text-gray-100">{title}</h1><p className="mt-4 max-w-2xl mx-auto text-gray-600 dark:text-gray-400">{text}</p></div></section>}
function ContactItem({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex gap-3"><div className="p-3 rounded-xl bg-primary-50 text-primary-600 h-fit">{icon}</div><div><p className="font-semibold text-gray-900 dark:text-gray-100">{title}</p><p className="text-sm text-gray-500 mt-1">{text}</p></div></div>}
