import { useEffect, useState } from "react";
import { Heart, IndianRupee, Users, Target, Download } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import Card from "@/components/ui/Card";
import StatCard from "@/components/ui/StatCard";
import Badge from "@/components/ui/Badge";
import Button from "@/components/ui/Button";
import { supabase } from "@/lib/supabase";
import { downloadCSV, formatCurrency, formatDateTime } from "@/utils";
import type { Campaign, Donation, Profile } from "@/types";

export function AdminDashboardPage(){const [users,setUsers]=useState<Profile[]>([]);const [donations,setDonations]=useState<Donation[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);useEffect(()=>{Promise.all([supabase.from("profiles").select("*"),supabase.from("donations").select("*, campaigns(*)").order("created_at",{ascending:false}),supabase.from("campaigns").select("*")]).then(([u,d,c])=>{setUsers(u.data??[]);setDonations(d.data??[]);setCampaigns(c.data??[])})},[]);const successful=donations.filter(d=>d.status==="success");return <DashboardLayout admin><div className="max-w-7xl mx-auto space-y-8"><div><p className="text-sm text-gray-500">Platform overview</p><h2 className="mt-1 text-3xl font-bold font-display">Admin Dashboard</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><StatCard label="Total Users" value={users.length} icon={Users} color="secondary"/><StatCard label="Total Raised" value={formatCurrency(successful.reduce((s,d)=>s+d.amount,0))} icon={IndianRupee} color="primary"/><StatCard label="Successful Donations" value={successful.length} icon={Heart} color="success"/><StatCard label="Active Campaigns" value={campaigns.filter(c=>c.status==="active").length} icon={Target} color="accent"/></div><Card padding="none"><div className="p-6 flex items-center justify-between"><div><h3 className="text-lg font-bold">Recent donations</h3><p className="text-sm text-gray-500 mt-1">Latest platform activity.</p></div><Button variant="outline" size="sm" leftIcon={<Download className="w-4 h-4"/>} onClick={()=>downloadCSV("all-donations.csv",donations.map(d=>({Donor:d.is_anonymous?"Anonymous Donor":d.donor_name,Amount:d.amount,Status:d.status,Date:formatDateTime(d.created_at),Transaction:d.transaction_id}))) }>Export CSV</Button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 dark:bg-gray-800 text-xs uppercase text-gray-500"><tr><th className="px-6 py-3">Donor</th><th className="px-6 py-3">Amount</th><th className="px-6 py-3">Status</th><th className="px-6 py-3">Date</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-gray-800">{donations.slice(0,10).map(d=><tr key={d.id}><td className="px-6 py-4 font-semibold">{d.is_anonymous?"Anonymous Donor":d.donor_name}</td><td className="px-6 py-4 font-bold">{formatCurrency(d.amount)}</td><td className="px-6 py-4"><Badge variant={d.status==="success"?"success":"warning"}>{d.status}</Badge></td><td className="px-6 py-4 text-gray-500">{formatDateTime(d.created_at)}</td></tr>)}</tbody></table></div></Card></div></DashboardLayout>}

export function AdminPlaceholderPage({title}:{title:string}){return <DashboardLayout admin><div className="max-w-7xl mx-auto"><h2 className="text-3xl font-bold font-display">{title}</h2><Card padding="lg" className="mt-8"><p className="text-gray-500">This admin workspace is ready for management actions. Use the dashboard export for the current live report.</p></Card></div></DashboardLayout>}
